bidding/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/products/highest_bidder' => 'products#highest_bidder'
  resources :users#, only: %i(new show create)
  resources :products#, only: %i(new show create index)
end

bidding/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bidding/app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  validates :amount, presence: true
  validates :unit, presence: true
  validates :user_id, presence: true
  validates :product_id, presence: true
end

bidding/app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true
  validates :photo, presence: true
  validates :price, presence: true
end

bidding/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true, uniqueness: { message: "This email is already used." } 

   def self.authenticate(email, password)
    user = User.find_by(email: email)

    return nil if user.nil?
    return user if user.password == password
  end
end

bidding/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include UsersHelper
end

bidding/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :signed_in?

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: "Product created."
    else
      render :new, error: "Product was not create"
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    respond_to do |format|
      format.html {
        if @product.update(product_params)
          flash[:notice] = "Product was updated."
        else
          flash[:error] = "Product was not updated"
        end
        redirect_to products_path
      }
      format.js {
        if @product.highest_bidder == current_user.email
          flash[:error] = "You are the highest bidder"
        elsif params[:product][:price].to_i <= @product.price * 1.1
          flash[:error] = "Minimal bidding price is #{@product.price * 1.1} (+10%)"
        else
          @product.highest_bidder = current_user.email
          @product.update(product_params)
        end
        
        redirect_to products_path
      }
    end

  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:notice] = "Successfully deleted entry"
    else
      flash[:error] = "Could not delete entry"
    end
    redirect_to products_path
  end

  def highest_bidder
    @products = Product.where(highest_bidder: current_user.email)
  end

  private

  def product_params
    params.require(:product).permit(:name, :photo, :price, :highest_bidder)
  end
end

bidding/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create  
    @user = User.find_by(email: params[:session][:email])
    if @user and @user.authenticate(params[:session][:password])
      sign_in @user
      redirect_to @user, notice: "Successfully logged in"
    else
      flash.now[:error] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    sign_out
    render :new, notice: "Successfully logged out"
  end
end

bidding/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.new
    @users = User.all
  end

  def new
    @user = User.new
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
 
    respond_to do |format|
      if @user.save
        format.html { 
          sign_in(@user)
          UserMailer.welcome_mail(@user).deliver_later
          redirect_to @user, notice: "User successfully created!" 
        }
        format.js   { redirect_to users_path }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end
  
  private

  def user_params 
    params.require(:user).permit(:email, :password)
  end
end

bidding/app/helpers/application_helper.rb
module ApplicationHelper
end

bidding/app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id]) 
    else
      deny_acces
    end
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    session[:user_id] = nil
    self.current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  def deny_acces
    redirect_to '/login', :notice => "Please sign in to acces this page"
  end

end

bidding/app/helpers/users_helper.rb
module UsersHelper
 def self.authenticate(email, password)
    user = User.find_by(email)

    return nil if user.nil?
    return user if user.has_password?(password)
  end
end

bidding/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bidding</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

bidding/app/views/products/edit.html.erb
<h2>Edit product</h2>

<%= form_for @product do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :photo %>
	<%= f.text_field :photo %>
	<%= f.label :price %>
	<%= f.text_field :price %>

	<%= f.submit %>
<% end %>

 

bidding/app/views/products/highest_bidder.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Photo</th>
    <th>Highest bidder</th>
  </tr>

  <tbody>
    <% if @products.empty? %>
      <strong> No products yet</strong>
    <% else %>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><img src="<%= product.photo %>" style="width:200px"></td>
          <td><%= product.price %>$  <%= product.highest_bidder %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to('Go back to products', '/products') %>

bidding/app/views/products/index.html.erb
<h3> Products </h3>

<% if flash[:error] %>
  <p><%= flash[:error] %></p>
<% end %>


<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>


<table>
  <tr>
    <th>Name</th>
    <th>Photo</th>
    <th>Price</th>
    <th>Highest bidder</th>
    <th colspan="2">Options</th>
    <th colspan="2">Raise</th>
  </tr>

  <tbody>
    <% if @products.empty? %>
      <strong> No products yet</strong>
    <% else %>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><img src="<%= product.photo %>" style="width:200px"></td>
          <td><%= product.price %>$</td>
          <td><%= product.highest_bidder %></td>
          <td><%= link_to("Edit", edit_product_path(product.id)) %></td>
          <td><%= link_to("Destroy", product, method: :delete) %></td>
          <td>
            <%= form_for product, url:{ action: :update , id: product.id, highest_bidder: current_user.email}, remote: true do |f| %>
              <%= f.submit 'Place bid'%>
              <%= f.text_field :price %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to('Your highest bids', '/products/highest_bidder') %></br>
<%= link_to('Sign out', '/logout') %>

bidding/app/views/products/new.html.erb
<h2>Create product</h2>

<%= form_for @product do |f| %>
	Name: <%= f.text_field :name %>
	Photo url: <%= f.text_field :photo %>
	Price: <%= f.text_field :price %>

	<%= f.submit %>
<% end %>

bidding/app/views/products/show.html.erb
<%= @product.inspect %>

bidding/app/views/users/index.html.erb
<h2>All users</h2>

<table>
	<tr>
		<th>id</th>
		<th>email</th>
		<th>Options</th>
	</tr>

	<tbody>
		<% if @users.empty? %>
      <strong> No users yet</strong>
    <% else %>
    	<% @users.each do |user| %>
    		<tr>
    			<td><%= user.id %></td>
    			<td><%= user.email %></td>
    			<td><%= link_to 'Destroy', user, method: :delete %></td>
    		</tr>
    	<% end %>
		<% end %>
	</tbody>
</table></br>
 
<%= form_for(@user, remote: true) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  
  <%= f.submit %>
<% end %>

bidding/app/views/users/new.html.erb
<h2>Create user</h2>

<%= form_for @user do |f| %>
	<%= f.label :email %>
	<%= f.text_field :email %>
	<%= f.label :password %>
	<%= f.password_field :password %>

	<%= f.submit %>
<% end %>

<%= link_to("Log in", '/login') %> 

bidding/app/views/users/show.html.erb
<h2>Hi, <%= @user.email %>! </h2> 

<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<%= link_to("Products", '/products') %></br>
<%= link_to("Log out", '/login') %>

bidding/app/views/users/signin.html.erb
<h3> Sign in </h3>

<%= form_for :user do |f| %>
	<%= f.label :email %> 
	<%= f.text_field :email %>
	<%= f.label :password %> 
	<%= f.password_field :password %>

	<%= f.submit 'Log in' %>
<% end %>

</br><%= link_to("Sign up", new_user_path) %>